# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170413_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 19, 16, 38, 1, 7809, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
